"""Adiciona estrutura de metas orçamentárias

Revision ID: 0d43d5bf95c2
Revises: e8f9a3b2c4d5
Create Date: 2025-07-31 08:24:47.722313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d43d5bf95c2'
down_revision = 'e8f9a3b2c4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor_limite', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('periodo', sa.String(length=20), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('alertar_percentual', sa.Integer(), nullable=True),
    sa.Column('renovar_automaticamente', sa.Boolean(), nullable=True),
    sa.Column('incluir_cartao', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metas_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('mes_referencia', sa.Date(), nullable=False),
    sa.Column('valor_gasto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_limite', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meta_id'], ['metas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metas_historico')
    op.drop_table('metas')
    # ### end Alembic commands ###
