"""Adiciona campo tag na tabela lancamentos

Revision ID: 15f43e02e8f5
Revises: 3f8247231bbb
Create Date: 2025-07-30 12:01:32.234562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f43e02e8f5'
down_revision = '3f8247231bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.drop_column('tag')

    # ### end Alembic commands ###
