"""Adiciona tabela de historico de saldos de investimentos

Revision ID: e55e38ba4c79
Revises: 0d43d5bf95c2
Create Date: 2025-07-31 15:40:06.065292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55e38ba4c79'
down_revision = '0d43d5bf95c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saldos_investimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.Date(), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rendimento_mes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('percentual_mes', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conta_id', 'data_registro', name='_conta_data_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saldos_investimentos')
    # ### end Alembic commands ###
